FROM node:12 as builder

WORKDIR /frontend

COPY package.json ./package.json
RUN npm install
COPY . .

CMD ["npm", "run", "build"]

FROM nginx 
EXPOSE 3000
COPY ./defalut.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend/build /usr/share/nginx/html