FROM python:3.9.0

ENV PYTHONBUFFERED 1

RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir /django
WORKDIR /django

ADD requirements.txt /django/

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python -m textblob.download_corpora


ADD . /django/

RUN python manage.py collectstatic --noinput