# Generated by Django 3.1.7 on 2021-04-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_character_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='mvti',
            field=models.CharField(default='', max_length=4, verbose_name='mvti type'),
        ),
    ]
